<a href="https://colab.research.google.com/github/Ahmad-Momani/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# also see https://pytorch.org/docs/stable/tensors.html

**Tensors Initialization**

In [13]:
# using creation operation: torch.*(shape), *:creation operation like ones and zeros
# aslo see https://pytorch.org/docs/stable/torch.html#tensor-creation-ops
shape = (2,3)
tensor1 = torch.ones(shape)
# from data
      # pre-existing data: torch.tensor(data)
tensor2 = torch.tensor([[1., -1.], [1., -1.]])
      # pre-existing numpy array: torch.from_numpy(np_array)
tensor3 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
      # from another tensor: 
         # torch.*_like(x_data), *:creation operation 
tensor4 = torch.ones_like(tensor3)
         # tensor.new_*(shape) : the returned Tensor has the same torch.dtype and torch.device as this tensor
tensor5 = tensor4.new_zeros((3,3))

print(tensor1)
print(tensor2)
print(tensor3)
print(tensor4)
print(tensor5)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 1., -1.],
        [ 1., -1.]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


**Operations on Tensors**

In [ ]:
# matrix manipulation
   # indexing 
   # slicing
   # joining
   # Mutating
   # transposing

# Arithmetic operations

# linear algebra

# in-place operations



**Bridge to numpy**

In [ ]:
# numpy to tensor

# tensor to numpy