<a href="https://colab.research.google.com/github/Ahmad-Momani/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# also see https://pytorch.org/docs/stable/tensors.html

**Tensors Initialization**

In [7]:
# using creation operation: torch.*(shape), *:creation operation like ones and zeros
# aslo see https://pytorch.org/docs/stable/torch.html#tensor-creation-ops
shape = (2,3)
ones_tensor = torch.ones(shape)
print(ones_tensor)
# from data
      # pre-existing data: torch.tensor(data)
      # pre-existing numpy array: torch.from_numpy(np_array)
      # from another tensor: 
         # torch.*_like(x_data), *:creation operation 
         # tensor.new_* : the returned Tensor has the same torch.dtype and torch.device as this tensor

tensor([[0.3314, 0.5754, 0.6505],
        [0.2729, 0.0783, 0.9042]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
